language: node_js
node_js:
- node
before_deploy:
- npm run build
deploy:
  provider: npm
  email: anthony.kerz@gmail.com
  api_key:
    secure: gf+Z9HgpW7VTHJUBOFrFNrGVBi9+9k/xIumfN873hQohbYyB++H5NmdhxpDkuybXoIt4SnKHORkUvjt1GvEj+dkivRf4HfDPXfakzbZDEup3g/iUyzFj8s76uR0abtC75qi+8QOCVDpsrn3kvZBjWsFjdocbx4yisukQH4qIkJuDaL1SNK8fQPy59EmGSa0kL+pHfCL6twAPEK9JtCmFBtiLmq3uZCWmxPHsWNjo3NfDghXW5B092CSQLcRvWZwk2cL4zWydIJA3GcZr8k72voYCMIXGk8djSAYjxshdbei2pmGwMJ4yYEbCFmNUVxmxthENGZrra6+TLwWYfOQ/uLJQhlclRWXYRe/bQ7xdqBephLhJtSiMSY6TvaNcwY4O4bUzVWN1vfRS/eo31rkdf05ohudXr7siaifevy8yLMbDn1WlDKmXFZ0frFeGF6Nx1PE2n8Uhrk3J1x9MBQS27BQeOo74X0/L0AeaUay4NRREMySUAk+eoE0R948AzmzVNRUzZYV7kkee+4NE0xtJyNHY6R5S3v3/gD1Oe6QoNN0j7cTxmXBxeovoabD8Iv/2UCx6AA8+wU79xDBDlIP9jhDtv2he6Vttwy8FoCDgHQbKWcCC20+SlVilmTWs6S1+ga1xTeiiji+XUwk7cnOf9IdDXlI4MHzbeNK03kMCdvk=
  skip_cleanup: true
  on:
    branch: master
    condition: "-z $TRAVIS_TAG"
